<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BetterTranslator.Core\BetterTranslator.Core.csproj" />
  </ItemGroup>

</Project>
